
services:
  opal-user-db:
    container_name: opal-user-db
    image: postgres:17
    restart: always
    environment:
      - POSTGRES_DB=opal-user-db
      - POSTGRES_USER=opal-user
      - POSTGRES_PASSWORD=opal-user
      - PGPORT=5432
    ports:
      - "5433:5432"
    volumes:
      - opal_user_db_data:/var/lib/postgresql/data

  opal-user-service:
    build:
      context: .
      args:
        - http_proxy
        - https_proxy
        - no_proxy
    image: hmctspublic.azurecr.io/opal/user-service
    environment:
      # these environment variables are used by java-logging library
      - ROOT_APPENDER
      - JSON_CONSOLE_PRETTY_PRINT
      - ROOT_LOGGING_LEVEL
      - REFORM_SERVICE_TYPE
      - REFORM_SERVICE_NAME
      - REFORM_TEAM
      - REFORM_ENVIRONMENT
      - LOGBACK_DATE_FORMAT
      - LOGBACK_REQUIRE_THREAD
      - LOGBACK_REQUIRE_ALERT_LEVEL=false
      - LOGBACK_REQUIRE_ERROR_CODE=false
      - OPAL_USER_DB_HOST=opal-user-db
    ports:
      - $SERVER_PORT:$SERVER_PORT

volumes:
  opal_user_db_data:
