apiVersion: v2
appVersion: "1.0"
description: A Helm chart for opal-user-service App
name: opal-user-service
home: https://github.com/hmcts/opal-user-service
version: 0.0.35
maintainers:
  - name: HMCTS opal team
dependencies:
  - name: java
    version: 5.3.0
    repository: 'oci://hmctspublic.azurecr.io/helm'
