java:
  applicationPort: 4555
  image: 'sdshmctspublic.azurecr.io/opal/user-service:latest'
  ingressHost: opal-user-service.{{ .Values.global.environment }}.platform.hmcts.net
  aadIdentityName: opal
  keyVaults:
    opal:
      secrets:
        - name: app-insights-connection-string
          alias: app-insights-connection-string
        - name: user-service-POSTGRES-HOST
          alias: OPAL_USER_DB_HOST
        - name: user-service-POSTGRES-PASS
          alias: OPAL_USER_DB_PASSWORD
        - name: user-service-POSTGRES-PORT
          alias: OPAL_USER_DB_PORT
        - name: user-service-POSTGRES-USER
          alias: OPAL_USER_DB_USERNAME
        - name: user-service-POSTGRES-DATABASE
          alias: OPAL_USER_DB_NAME
        - name: AzureADTenantId
          alias: AAD_TENANT_ID
        - name: AzureADClientId
          alias: AAD_CLIENT_ID
        - name: AzureADClientSecret
          alias: AAD_CLIENT_SECRET
        - name: OpalTestUserPassword
          alias: OPAL_TEST_USER_PASSWORD

  environment:
    RUN_DB_MIGRATION_ON_STARTUP: true
    OPAL_FRONTEND_URL: https://opal-frontend.{{ .Values.global.environment }}.platform.hmcts.net
    TESTING_SUPPORT_ENDPOINTS_ENABLED: true
    LAUNCH_DARKLY_ENABLED: true
  postgresql:
    enabled: false
    image:
      tag: '17.5.0'
