java:
  # Don't modify below here
  image: ${IMAGE_NAME}
  ingressHost: ${SERVICE_FQDN}
  devmemoryRequests: "1Gi"
  devcpuRequests: "250m"
  devmemoryLimits: "2Gi"
  devcpuLimits: "2500m"
  keyVaults:
    opal:
      secrets:
        - name: app-insights-connection-string
          alias: app-insights-connection-string
  environment:
    OPAL_USER_DB_HOST: "{{ .Release.Name }}-postgresql"
    OPAL_USER_DB_NAME: "{{ .Values.postgresql.auth.database}}"
    OPAL_USER_DB_USERNAME: "{{ .Values.postgresql.auth.username}}"
    OPAL_USER_DB_PASSWORD: "{{ .Values.postgresql.auth.password}}"
    OPAL_USER_DB_OPTIONS: "?stringtype=unspecified"
    OPAL_USER_DB_PORT: 5432
    RUN_DB_MIGRATION_ON_STARTUP: true
  postgresql:
    enabled: true
