java:
  applicationPort: 4555
  image: 'sdshmctpsublic.azurecr.io/opal/user-service:latest'
  ingressHost: opal-user-service-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
  aadIdentityName: opal
  keyVaults:
    opal:
      secrets:
        - name: app-insights-connection-string
          alias: app-insights-connection-string
        - name: user-service-POSTGRES-HOST
          alias: OPAL_USER_DB_HOST
        - name: user-service-POSTGRES-PASS
          alias: OPAL_USER_DB_PASSWORD
        - name: user-service-POSTGRES-PORT
          alias: OPAL_USER_DB_PORT
        - name: user-service-POSTGRES-USER
          alias: OPAL_USER_DB_USERNAME
        - name: user-service-POSTGRES-DATABASE
          alias: OPAL_USER_DB_NAME  

  environment:
    RUN_DB_MIGRATION_ON_STARTUP: true
